### PR TITLE
Add missing sentence for successful event sign up

### PR DESCRIPTION
**Pull request by fossil12**

### CODE REVIEW

**Comment by RolandStuder** [comment]
This sentence is usually not appropriate as this message is also shown for people who sign up themselves. And if you signup yourself you are shown you contact details first, as shown in the screenshot.

image

**Comment by fossil12** [comment]
Thank you for the feedback. It was a request by the course administration. I will hand the feedback back.

**Comment by RolandStuder** [comment]
Of course it would be possible to display different messages, but that is a bit more work.

**Comment by fossil12** [comment]
Okay. I wait for the response I get to you feedback.

BTW: In the generic version this sentence still exists: https://github.com/hitobito/hitobito/blob/master/config/locales/views.de.yml#L428

**Comment by kronn** [comment]
It this issue still relevant/wanted/needed, @fossil12 ? 

if the sentence from the core is more appropriate, we could remove the overwritten sentence and just use the original one. (https://github.com/hitobito/hitobito/blob/master/config/locales/views.de.yml#L457) @RolandStuder is still right IMHO, but I want to move this forward or close it.

**Comment by fossil12** [comment]
@kronn Oh, that is old. :) Maybe I read something wrong, but the core sentence is exactly this change, isn't it?

**Comment by kronn** [comment]
@fossil12 yes. I see no problem in changing it, I just do not know which version is wanted/expected.

Personally, I would just remove the translation from the `hitobito_jubla`-wagon, which would lead to the core-translations to be visible again.

**Comment by fossil12** [comment]
@kronn Then let's remove this translation from the `hitobito_jubla`-wagon.

**Comment by kronn** [comment]
Thanks for your help in resolving this, @fossil12 :-)

**Pull request closed without merging**
